from dataclasses import dataclass

from devtools.settings import (
    DEV_SOURCE_API_URL,
    DEV_SOURCE_DB_URL,
    DEV_SOURCE_FILE_DIR,
    DEV_TARGET_API_URL,
    DEV_TARGET_DB_URL,
    DEV_TARGET_FILE_DIR,
)
from devtools.tools.dev_orm import DevSourceDataText, DevTargetDataText
from pluggle.enums import ContentFormat, PluggleIOType

"""
Devtools test packages — pre-configured InputArgs kwargs sets for rapid
manual pipeline testing via `pluggle-dev test --inject <key>`.

This module is a living catalog of test scenarios, not an exhaustive
suite. New packages should be added as new source/target combinations,
error cases, or edge cases become relevant to test manually.
"""


@dataclass
class TestPackage:
    source_type: PluggleIOType
    source_address: str
    target_type: PluggleIOType
    target_address: str
    transform_strategy_name: str
    source_table: str | None = None
    target_table: str | None = None
    target_format: ContentFormat = ContentFormat.JSON


TEST_PACKAGES: dict[int, TestPackage] = {
    1: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "comments.json"),
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_json.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    2: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "comments.json"),
        target_type=PluggleIOType.DB,
        target_address=str(DEV_TARGET_DB_URL),
        transform_strategy_name="strategy-for-sample-comments-json_v1.0",
        source_table=None,
        target_table=DevTargetDataText.__tablename__,
        target_format=ContentFormat.JSON,
    ),
    3: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "comments.json"),
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    4: TestPackage(
        source_type=PluggleIOType.DB,
        source_address=str(DEV_SOURCE_DB_URL),
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_db.json"),
        transform_strategy_name="default_v1.0",
        source_table=DevSourceDataText.__tablename__,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    5: TestPackage(
        source_type=PluggleIOType.DB,
        source_address=str(DEV_SOURCE_DB_URL),
        target_type=PluggleIOType.DB,
        target_address=str(DEV_TARGET_DB_URL),
        transform_strategy_name="default_v1.0",
        source_table=DevSourceDataText.__tablename__,
        target_table=DevTargetDataText.__tablename__,
        target_format=ContentFormat.JSON,
    ),
    6: TestPackage(
        source_type=PluggleIOType.DB,
        source_address=str(DEV_SOURCE_DB_URL),
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=DevSourceDataText.__tablename__,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    7: TestPackage(
        source_type=PluggleIOType.API,
        source_address=str(DEV_SOURCE_API_URL),
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_api.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    8: TestPackage(
        source_type=PluggleIOType.API,
        source_address=str(DEV_SOURCE_API_URL),
        target_type=PluggleIOType.DB,
        target_address=str(DEV_TARGET_DB_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=DevTargetDataText.__tablename__,
        target_format=ContentFormat.JSON,
    ),
    9: TestPackage(
        source_type=PluggleIOType.API,
        source_address=str(DEV_SOURCE_API_URL),
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    10: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "cities.csv"),
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_csv.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    11: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "cities.csv"),
        target_type=PluggleIOType.DB,
        target_address=str(DEV_TARGET_DB_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=DevTargetDataText.__tablename__,
        target_format=ContentFormat.JSON,
    ),
    12: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "cities.csv"),
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    13: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "The World Wide Web project.htm"),
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_html.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    14: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "The World Wide Web project.htm"),
        target_type=PluggleIOType.DB,
        target_address=str(DEV_TARGET_DB_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=DevTargetDataText.__tablename__,
        target_format=ContentFormat.JSON,
    ),
    15: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "The World Wide Web project.htm"),
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    16: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "cd_catalog.xml"),
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_xml.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    17: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "cd_catalog.xml"),
        target_type=PluggleIOType.DB,
        target_address=str(DEV_TARGET_DB_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=DevTargetDataText.__tablename__,
        target_format=ContentFormat.JSON,
    ),
    18: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "cd_catalog.xml"),
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    19: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "sample-files.com-basic-text.docx"),
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_docx.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    20: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "sample-files.com-basic-text.docx"),
        target_type=PluggleIOType.DB,
        target_address=str(DEV_TARGET_DB_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=DevTargetDataText.__tablename__,
        target_format=ContentFormat.JSON,
    ),
    21: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "sample-files.com-basic-text.docx"),
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    22: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "Free_Test_Data_100KB_XLSX.xlsx"),
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_xlsx.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    23: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "Free_Test_Data_100KB_XLSX.xlsx"),
        target_type=PluggleIOType.DB,
        target_address=str(DEV_TARGET_DB_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=DevTargetDataText.__tablename__,
        target_format=ContentFormat.JSON,
    ),
    24: TestPackage(
        source_type=PluggleIOType.FILE,
        source_address=str(DEV_SOURCE_FILE_DIR / "Free_Test_Data_100KB_XLSX.xlsx"),
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    25: TestPackage(
        source_type=PluggleIOType.API,
        source_address="https://www.federalregister.gov/api/v1/documents.csv?per_page=5",
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_api_csv.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    26: TestPackage(
        source_type=PluggleIOType.DB,
        source_address="postgresql://postgres:testpass@localhost:5432/postgres",
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_postgres.json"),
        transform_strategy_name="default_v1.0",
        source_table="dialect_check",
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    27: TestPackage(
        source_type=PluggleIOType.API,
        source_address="https://www.federalregister.gov/api/v1/documents.csv?per_page=5",
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    28: TestPackage(
        source_type=PluggleIOType.API,
        source_address="https://www.nasa.gov/feed/",
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    29: TestPackage(
        source_type=PluggleIOType.API,
        source_address="https://www.example.org/",
        target_type=PluggleIOType.API,
        target_address=str(DEV_TARGET_API_URL),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    30: TestPackage(
        source_type=PluggleIOType.API,
        source_address="https://www.nasa.gov/feed/",
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_api_xml.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
    31: TestPackage(
        source_type=PluggleIOType.API,
        source_address="https://www.example.org/",
        target_type=PluggleIOType.FILE,
        target_address=str(DEV_TARGET_FILE_DIR / "output_api_html.json"),
        transform_strategy_name="default_v1.0",
        source_table=None,
        target_table=None,
        target_format=ContentFormat.JSON,
    ),
}
